server:
  port: 8001

spring:
  application:
    name: NationalDosagePlatform
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: FebsHikariCP
      # 配置默认数据源
      primary: base
      datasource:
        # 数据源-1，名称为 base
        base:
          username: db_user
          password: 1QAZ2wsx!@
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://39.105.48.210:3306/nation_dosage?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8

mybatis-plus:
  # 实体类扫描路径
  type-aliases-package: com.evision.dosage.pojo.entity.*
  # xml 扫描路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

## 配置Cookie的Domain
cookie:
  domain: 39.105.48.210

## 百度地图AK
baidu:
  ak: GqrxIljRESHDNbxri4zGHA8FQKgaGhTI

logging:
  level:
    com.evision.dosage.mapper: debug

